name: Deploy Backend

on:
  push:
    branches: [main]
    paths: ["backend/**"] # só roda se mudar backend

env:
  PROJECT_ID: lastbit-prj-d-movieapi
  REGION: us-central1
  ARTIFACT_REGISTRY: movieapi
  IMAGE_NAME: app-mooovi-backend
  RUN_SERVICE_NAME: run-backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ./backend
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # TMDB_API_KEY já configurado no Cloud Run (Secret Manager). Secret: FRONTEND_URL (URL do frontend)
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.RUN_SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --project ${{ env.PROJECT_ID }} \
            --allow-unauthenticated \
            --set-env-vars="CORS_ORIGIN=${{ secrets.FRONTEND_URL }}"
